/**
 * Stage 3C — genuine engine audit event.
 *
 * Every field is copied verbatim from what the existing engine/logger already
 * supplies. Nothing is inferred, defaulted or fabricated: a value the engine
 * did not provide is simply absent (null).
 */

import type { DecisionLogEntry } from '@/types/trading';

export type EngineAuditEventType = DecisionLogEntry['action'];

export interface EngineAuditProvenance {
  engineModified: false;
  observerOnly: true;
}

export interface EngineAuditEvent {
  /** Immutable id generated by the engine's logger. */
  eventId: string;
  /** Engine-supplied event timestamp (ms). */
  timestamp: number;
  asset: string;
  eventType: EngineAuditEventType;
  /** Engine-supplied signal / decision, when the engine provided one. */
  signal: string | null;
  /** Engine-authored plain-English reason. */
  explanation: string;
  regime: string | null;
  filterBlocked: string | null;
  sourceModule: 'logger';
  /** When the observer persisted the event (observation time, not decision time). */
  capturedAt: number;
  provenance: EngineAuditProvenance;
}

export interface AuditSummary {
  total: number;
  byType: Record<string, number>;
  assets: string[];
  latestTimestamp: number | null;
}

export interface AuditStorageStatus {
  available: boolean;
  persisted: number;
  lastError: string | null;
}
