/**
 * Stage 3C — genuine engine audit event.
 *
 * Every field is copied verbatim from what the existing engine/logger already
 * supplies. Nothing is inferred, defaulted or fabricated: a value the engine
 * did not provide is simply absent (null).
 */

import type { DecisionLogEntry } from '@/types/trading';

export type EngineAuditEventType = DecisionLogEntry['action'];

/**
 * Where an audit record came from.
 *  - 'logger' : live, contemporaneous decision published by the engine logger.
 *  - 'trades' : completed simulated trade read back from the persisted
 *               TradingContext trade history (observed AFTER execution).
 */
export type EngineAuditSource = 'logger' | 'trades';

export interface EngineAuditProvenance {
  engineModified: false;
  observerOnly: true;
}

export interface EngineAuditEvent {
  /** Immutable id generated by the engine's logger. */
  eventId: string;
  /** Engine-supplied event timestamp (ms). */
  timestamp: number;
  asset: string;
  eventType: EngineAuditEventType;
  /** Engine-supplied signal / decision, when the engine provided one. */
  signal: string | null;
  /** Engine-authored plain-English reason. */
  explanation: string;
  regime: string | null;
  filterBlocked: string | null;
  sourceModule: EngineAuditSource;
  /** True when the record was reconstructed from persisted trade history. */
  backfilled: boolean;
  /**
   * False when the record was observed after the fact — such records must
   * NEVER be given a current CMC snapshot (it would not be the environment
   * that existed at decision time).
   */
  contextContemporaneous: boolean;
  /** When the observer persisted the event (observation time, not decision time). */
  capturedAt: number;
  provenance: EngineAuditProvenance;
}

export interface AuditSummary {
  total: number;
  live: number;
  backfilled: number;
  byType: Record<string, number>;
  assets: string[];
  latestTimestamp: number | null;
}

export interface AuditStorageStatus {
  available: boolean;
  persisted: number;
  lastError: string | null;
}
