import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Suspense, lazy } from "react";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AppLayout } from "@/components/AppLayout";
import { ExecPageSkeleton } from "@/components/executive/ExecUi";
const MaintenanceExecutive = lazy(() => import("./pages/maintenance/MaintenanceExecutive"));
const MaintenanceInstitutionHealth = lazy(() => import("./pages/maintenance/MaintenanceInstitutionHealth"));
const MaintenanceModules = lazy(() => import("./pages/maintenance/MaintenanceModules"));
const MaintenanceWorkflows = lazy(() => import("./pages/maintenance/MaintenanceWorkflows"));
const MaintenanceGovernanceAuditor = lazy(() => import("./pages/maintenance/MaintenanceGovernance"));
const MaintenanceDatabase = lazy(() => import("./pages/maintenance/MaintenanceDatabase"));
const MaintenanceKnowledge = lazy(() => import("./pages/maintenance/MaintenanceKnowledge"));
const MaintenancePerformanceCentre = lazy(() => import("./pages/maintenance/MaintenancePerformance"));
const MaintenanceAutoRepair = lazy(() => import("./pages/maintenance/MaintenanceAutoRepair"));
const MaintenancePredictive = lazy(() => import("./pages/maintenance/MaintenancePredictive"));
const MaintenanceReportsPage = lazy(() => import("./pages/maintenance/MaintenanceReports"));
const MaintenanceSettingsPage = lazy(() => import("./pages/maintenance/MaintenanceSettings"));
import Overview from "./pages/Overview";
const Trading = lazy(() => import("./pages/Trading"));
const Backtest = lazy(() => import("./pages/Backtest"));
const PaperTrading = lazy(() => import("./pages/PaperTrading"));
const DualPaperTrading = lazy(() => import("./pages/DualPaperTrading"));
const ChampionshipArena = lazy(() => import("./pages/ChampionshipArena"));
const PromotionReviewBoard = lazy(() => import("./pages/PromotionReviewBoard"));
const ResearchFreezeMode = lazy(() => import("./pages/ResearchFreezeMode"));
const PortfolioManager = lazy(() => import("./pages/PortfolioManager"));
const InvestmentCommittee = lazy(() => import("./pages/InvestmentCommittee"));
const ResearchJournal = lazy(() => import("./pages/ResearchJournal"));
const ExecutiveDashboard = lazy(() => import("./pages/ExecutiveDashboard"));
const MonthlyResearchReport = lazy(() => import("./pages/MonthlyResearchReport"));
const MarketMoveCapture = lazy(() => import("./pages/MarketMoveCapture"));
const MomentumScalper = lazy(() => import("./pages/MomentumScalper"));
const MomentumScalperV2 = lazy(() => import("./pages/MomentumScalperV2"));
const VolatilityCompressionBreakout = lazy(() => import("./pages/VolatilityCompressionBreakout"));
const SpecialistAllocationLab = lazy(() => import("./pages/SpecialistAllocationLab"));
const SpecialistAllocationLabV2 = lazy(() => import("./pages/SpecialistAllocationLabV2"));
const ForwardValidation = lazy(() => import("./pages/ForwardValidation"));
const ChampionTrial = lazy(() => import("./pages/ChampionTrial"));
const SpecialistChampionship = lazy(() => import("./pages/SpecialistChampionship"));
const SpecialistDiscoveryLabV2 = lazy(() => import("./pages/SpecialistDiscoveryLabV2"));
const LowVolCoilerV1 = lazy(() => import("./pages/LowVolCoilerV1"));
const LowVolCoilerV2 = lazy(() => import("./pages/LowVolCoilerV2"));
const SpecialistApprovalBoard = lazy(() => import("./pages/SpecialistApprovalBoard"));
const PortfolioArchitectureReview = lazy(() => import("./pages/PortfolioArchitectureReview"));
const ExecutiveProgramStatus = lazy(() => import("./pages/ExecutiveProgramStatus"));
const ObservationCenter = lazy(() => import("./pages/ObservationCenter"));
const AllocationProductionPath = lazy(() => import("./pages/AllocationProductionPath"));
const TradeFrequencyAudit = lazy(() => import("./pages/TradeFrequencyAudit"));
const RouterV21 = lazy(() => import("./pages/RouterV21"));
const PortfolioAIDirector = lazy(() => import("./pages/PortfolioAIDirector"));
const MissionControl = lazy(() => import("./pages/MissionControl"));
const ResearchAssistant = lazy(() => import("./pages/ResearchAssistant"));
const ChiefInvestmentOfficer = lazy(() => import("./pages/ChiefInvestmentOfficer"));
const AutonomousResearch = lazy(() => import("./pages/AutonomousResearch"));
const QuantScientist = lazy(() => import("./pages/QuantScientist"));
const IntelligenceNetwork = lazy(() => import("./pages/IntelligenceNetwork"));
const ResearchBrain = lazy(() => import("./pages/ResearchBrain"));
const Atlas = lazy(() => import("./pages/Atlas"));
const KnowledgeGraph = lazy(() => import("./pages/KnowledgeGraph"));
const IntelligenceExplorer = lazy(() => import("./pages/IntelligenceExplorer"));
const AtlasOracle = lazy(() => import("./pages/AtlasOracle"));
const ExecutiveBoardroom = lazy(() => import("./pages/ExecutiveBoardroom"));
const DigitalTwin = lazy(() => import("./pages/DigitalTwin"));
const Strategies = lazy(() => import("./pages/Strategies"));
const Portfolio = lazy(() => import("./pages/Portfolio"));
const Governance = lazy(() => import("./pages/Governance"));
const OperatorControls = lazy(() => import("./pages/OperatorControls"));
const Alerts = lazy(() => import("./pages/Alerts"));
const Experiments = lazy(() => import("./pages/Experiments"));
const Readiness = lazy(() => import("./pages/Readiness"));
const Research = lazy(() => import("./pages/Research"));
const SystemHealth = lazy(() => import("./pages/SystemHealth"));
const Promotion = lazy(() => import("./pages/Promotion"));
const SessionAnalytics = lazy(() => import("./pages/SessionAnalytics"));
const AnalyticsHub = lazy(() => import("./pages/AnalyticsHub"));
const WeeklyReview = lazy(() => import("./pages/WeeklyReview"));
const CommandCenter = lazy(() => import("./pages/CommandCenter"));
const BaselineValidation = lazy(() => import("./pages/BaselineValidation"));
const ParticipationController = lazy(() => import("./pages/ParticipationController"));
const Institution = lazy(() => import("./pages/Institution"));
const InstitutionDepartments = lazy(() => import("./pages/InstitutionDepartments"));
const InstitutionDepartment = lazy(() => import("./pages/InstitutionDepartment"));
const InstitutionCollaboration = lazy(() => import("./pages/InstitutionCollaboration"));
const InstitutionCalendar = lazy(() => import("./pages/InstitutionCalendar"));
const InstitutionQueue = lazy(() => import("./pages/InstitutionQueue"));
const InstitutionAnalytics = lazy(() => import("./pages/InstitutionAnalytics"));
const InstitutionScore = lazy(() => import("./pages/InstitutionScore"));
const InstitutionHistory = lazy(() => import("./pages/InstitutionHistory"));
const InstitutionMuseum = lazy(() => import("./pages/InstitutionMuseum"));
const InstitutionObservatory = lazy(() => import("./pages/InstitutionObservatory"));
const InstitutionCycle = lazy(() => import("./pages/InstitutionCycle"));
const InstitutionConversationsLive = lazy(() => import("./pages/InstitutionConversations"));
const InstitutionDecisions = lazy(() => import("./pages/InstitutionDecisions"));
const InstitutionEvolution = lazy(() => import("./pages/InstitutionEvolution"));
const InstitutionForecast = lazy(() => import("./pages/InstitutionForecast"));
const BriefingRoom = lazy(() => import("./pages/BriefingRoom"));
const InstitutionGenome = lazy(() => import("./pages/InstitutionGenome"));
const InstitutionHealth = lazy(() => import("./pages/InstitutionHealth"));
const SelfReview = lazy(() => import("./pages/SelfReview"));
const InstitutionLearning = lazy(() => import("./pages/InstitutionLearning"));
const InstitutionRecommendations = lazy(() => import("./pages/InstitutionRecommendations"));
const InstitutionQuality = lazy(() => import("./pages/InstitutionQuality"));
const InstitutionExplain = lazy(() => import("./pages/InstitutionExplain"));
const InstitutionBenchmark = lazy(() => import("./pages/InstitutionBenchmark"));
const ExecutiveSimulator = lazy(() => import("./pages/ExecutiveSimulator"));
const InstitutionRiskRadar = lazy(() => import("./pages/InstitutionRiskRadar"));
const InstitutionIQ = lazy(() => import("./pages/InstitutionIQ"));
const InstitutionEvolutionTimeline = lazy(() => import("./pages/InstitutionEvolutionTimeline"));
const ExecutiveHome = lazy(() => import("./pages/ExecutiveHome"));
const PerformanceCentre = lazy(() => import("./pages/PerformanceCentre"));
const EnterpriseSettings = lazy(() => import("./pages/EnterpriseSettings"));
const DocumentationCentre = lazy(() => import("./pages/DocumentationCentre"));
const MetricsApi = lazy(() => import("./pages/MetricsApi"));
const PresentationMode = lazy(() => import("./pages/PresentationMode"));
const LaunchChecklist = lazy(() => import("./pages/LaunchChecklist"));
const ExtensionManager = lazy(() => import("./pages/ExtensionManager"));
const AppMarketplace = lazy(() => import("./pages/AppMarketplace"));
const PluginSdk = lazy(() => import("./pages/PluginSdk"));
const ThemeEngine = lazy(() => import("./pages/ThemeEngine"));
const InstitutionTemplates = lazy(() => import("./pages/InstitutionTemplates"));
const WorkflowDesigner = lazy(() => import("./pages/WorkflowDesigner"));
const InstitutionPackagePage = lazy(() => import("./pages/InstitutionPackagePage"));
const DeveloperCentre = lazy(() => import("./pages/DeveloperCentre"));
const InstitutionCertification = lazy(() => import("./pages/InstitutionCertification"));
const FutureRoadmap = lazy(() => import("./pages/FutureRoadmap"));
const TestValidationCentre = lazy(() => import("./pages/TestValidationCentre"));
const AcceptanceProgramme = lazy(() => import("./pages/AcceptanceProgramme"));
const ReleaseCandidateCentre = lazy(() => import("./pages/ReleaseCandidateCentre"));
import NotFound from "./pages/NotFound";


const queryClient = new QueryClient();

/** Institutional route-level loading state. Matches executive page rhythm. */
const RouteFallback = () => (
  <div className="mx-auto w-full max-w-[1600px] p-6 sm:p-8">
    <ExecPageSkeleton />
  </div>
);

const App = () => (
  <QueryClientProvider client={queryClient}>
        <div>hi</div>
  </QueryClientProvider>
);

export default App;
